export type AgentStatus = "active" | "inactive" | "paused";

export interface AgentRule {
  id: string;
  label: string;
  value: string;
}

export interface AgentData {
  id: string;
  name: string;
  description: string;
  avatar: string;
  status: AgentStatus;
  type: string;
  earnings: string;
  trades: number;
  successRate: string;
  lastActive: string;
  category: string;
  rules: AgentRule[];
  budget: string;
  riskLevel: "low" | "medium" | "high";
  schedule: string;
  walletAddress: string;
  deployedAt: string;
  activityLog: { time: string; event: string; detail: string; kind: "success" | "info" | "warn" }[];
}

export const agents: AgentData[] = [
  {
    id: "alphaflow",
    name: "AlphaFlow",
    description: "Executes automated trading strategies across crypto markets, optimizing for volatility, momentum, and liquidity signals in real time.",
    avatar: "/figmaAssets/avatars-3.svg",
    status: "active",
    type: "Trading",
    earnings: "+$12,450",
    trades: 847,
    successRate: "73%",
    lastActive: "2 min ago",
    category: "DeFi",
    rules: [
      { id: "r1", label: "Max position size", value: "Never exceed 5% of total portfolio in a single trade." },
      { id: "r2", label: "Stop-loss", value: "Auto-close any position that drops more than 8% from entry." },
      { id: "r3", label: "Asset whitelist", value: "Only trade BTC, ETH, SOL, and top-20 DeFi tokens by market cap." },
      { id: "r4", label: "Momentum filter", value: "Only enter trades when RSI > 55 on the 1H timeframe." },
      { id: "r5", label: "Cool-down period", value: "Wait at least 10 minutes between consecutive trades on the same asset." },
    ],
    budget: "$10,000",
    riskLevel: "medium",
    schedule: "Continuous (24/7)",
    walletAddress: "0xAb34...f91C",
    deployedAt: "Mar 12, 2025",
    activityLog: [
      { time: "2m ago", event: "Trade executed", detail: "BUY 0.42 ETH @ $3,204 — momentum signal triggered", kind: "success" },
      { time: "18m ago", event: "Trade executed", detail: "SELL 1,200 SOL @ $148 — take-profit hit", kind: "success" },
      { time: "1h ago", event: "Signal skipped", detail: "RSI below threshold on BTC/USDT — no action taken", kind: "info" },
      { time: "3h ago", event: "Stop-loss triggered", detail: "AVAX position closed — -7.9% from entry", kind: "warn" },
      { time: "5h ago", event: "Trade executed", detail: "BUY 850 LINK @ $18.22 — breakout detected", kind: "success" },
    ],
  },
  {
    id: "yieldpilot",
    name: "Yield Pilot",
    description: "Manages capital allocation across DeFi protocols and yield strategies while maintaining risk-adjusted returns.",
    avatar: "/figmaAssets/avatars-9.svg",
    status: "active",
    type: "Yield",
    earnings: "+$8,201",
    trades: 312,
    successRate: "88%",
    lastActive: "5 min ago",
    category: "DeFi",
    rules: [
      { id: "r1", label: "Protocol whitelist", value: "Only deposit into Aave, Compound, Curve, Yearn, and Pendle." },
      { id: "r2", label: "Min APY threshold", value: "Do not deploy capital to any pool with less than 4% APY." },
      { id: "r3", label: "Diversification", value: "Never allocate more than 30% of capital to a single protocol." },
      { id: "r4", label: "Rebalance frequency", value: "Rebalance allocations every 24 hours or when APY deviation exceeds 2%." },
      { id: "r5", label: "Gas budget", value: "Do not execute rebalance if estimated gas cost exceeds 0.5% of yield gained." },
    ],
    budget: "$25,000",
    riskLevel: "low",
    schedule: "Every 24 hours",
    walletAddress: "0xCd78...a33E",
    deployedAt: "Jan 5, 2025",
    activityLog: [
      { time: "5m ago", event: "Rebalance", detail: "Moved $3,200 from Aave USDC (5.1%) → Pendle PT-USDC (8.4%)", kind: "success" },
      { time: "29h ago", event: "Rebalance", detail: "No action — APY deviation within tolerance", kind: "info" },
      { time: "2d ago", event: "Deposit", detail: "Added $2,000 to Curve 3pool — APY 6.2%", kind: "success" },
    ],
  },
  {
    id: "risksentinel",
    name: "Risk Sentinel",
    description: "Continuously monitors positions and transactions to detect anomalies, enforce limits, and prevent loss.",
    avatar: "/figmaAssets/avatars.svg",
    status: "active",
    type: "Risk",
    earnings: "$0",
    trades: 2103,
    successRate: "99%",
    lastActive: "Just now",
    category: "Security",
    rules: [
      { id: "r1", label: "Portfolio drawdown limit", value: "Alert and pause all agents if total portfolio drops 15% in 24h." },
      { id: "r2", label: "Unusual transaction alert", value: "Flag any single outbound transaction exceeding $5,000." },
      { id: "r3", label: "Smart contract risk", value: "Block interaction with any contract less than 30 days old or unaudited." },
      { id: "r4", label: "Wallet monitoring", value: "Watch connected wallets for unexpected approvals or drains." },
      { id: "r5", label: "Counterparty check", value: "Cross-check all counterparties against OFAC and known exploit lists." },
    ],
    budget: "N/A (monitoring only)",
    riskLevel: "low",
    schedule: "Continuous (24/7)",
    walletAddress: "0xF002...b11A",
    deployedAt: "Dec 1, 2024",
    activityLog: [
      { time: "Just now", event: "Scan complete", detail: "All positions within limits — no anomalies detected", kind: "info" },
      { time: "2h ago", event: "Alert raised", detail: "AlphaFlow AVAX stop-loss triggered — Risk Sentinel notified", kind: "warn" },
      { time: "6h ago", event: "Contract blocked", detail: "Blocked interaction with unverified token contract 0xba21...", kind: "warn" },
      { time: "1d ago", event: "Scan complete", detail: "Portfolio drawdown 4.2% — within acceptable range", kind: "info" },
    ],
  },
  {
    id: "signalseer",
    name: "Signal Seer",
    description: "Aggregates news, social signals, and on-chain data to surface actionable insights and trading signals.",
    avatar: "/figmaAssets/avatars-5.svg",
    status: "paused",
    type: "Analytics",
    earnings: "+$3,800",
    trades: 198,
    successRate: "61%",
    lastActive: "1 hour ago",
    category: "Analytics",
    rules: [
      { id: "r1", label: "Signal sources", value: "Monitor CoinTelegraph, The Block, Twitter/X crypto accounts with >50k followers, and Dune Analytics." },
      { id: "r2", label: "Sentiment threshold", value: "Only emit a bullish signal when at least 3 independent sources agree." },
      { id: "r3", label: "Signal confidence", value: "Tag signals with Low / Medium / High confidence before forwarding." },
      { id: "r4", label: "Noise filter", value: "Ignore signals related to meme coins and tokens with <$1M market cap." },
      { id: "r5", label: "Cooldown", value: "Do not emit more than 10 signals per 24-hour period." },
    ],
    budget: "$500 / month (API costs)",
    riskLevel: "low",
    schedule: "Hourly scans",
    walletAddress: "0x7e90...d44F",
    deployedAt: "Feb 20, 2025",
    activityLog: [
      { time: "1h ago", event: "Paused by user", detail: "Agent manually paused — resume when ready", kind: "warn" },
      { time: "2h ago", event: "Signal emitted", detail: "MEDIUM confidence: BTC breakout above $70k — 4/5 sources agree", kind: "success" },
      { time: "4h ago", event: "Signal skipped", detail: "Conflicting sentiment on ETH — only 2/5 sources bullish", kind: "info" },
    ],
  },
  {
    id: "inboxzero",
    name: "InboxZero",
    description: "Manages email, filters priority messages, and drafts replies automatically using AI.",
    avatar: "/figmaAssets/avatars-2.svg",
    status: "inactive",
    type: "Productivity",
    earnings: "+$240",
    trades: 0,
    successRate: "N/A",
    lastActive: "3 days ago",
    category: "Productivity",
    rules: [
      { id: "r1", label: "Priority senders", value: "Always flag emails from: team@brain.finance, investors, known VCs." },
      { id: "r2", label: "Auto-reply scope", value: "Only draft replies for meeting requests, partnership inquiries, and support tickets." },
      { id: "r3", label: "Tone", value: "Keep all drafted replies professional, concise, and under 200 words." },
      { id: "r4", label: "Exclusions", value: "Never auto-reply to marketing, newsletters, or no-reply addresses." },
      { id: "r5", label: "Human review", value: "Flag any email mentioning legal, contracts, or financial terms for human review." },
    ],
    budget: "$50 / month",
    riskLevel: "low",
    schedule: "Every 30 minutes",
    walletAddress: "N/A",
    deployedAt: "Nov 10, 2024",
    activityLog: [
      { time: "3d ago", event: "Deactivated", detail: "Agent stopped — no activity since deactivation", kind: "warn" },
      { time: "4d ago", event: "Draft created", detail: "Auto-drafted reply to partnership inquiry from 0xfund.io", kind: "success" },
      { time: "4d ago", event: "Email flagged", detail: "Legal mention detected — forwarded to human review", kind: "warn" },
    ],
  },
  {
    id: "trendradar",
    name: "TrendRadar",
    description: "Detects emerging trends across markets, social platforms, and ecosystems before they become mainstream.",
    avatar: "/figmaAssets/avatars-5.svg",
    status: "active",
    type: "Analytics",
    earnings: "+$5,100",
    trades: 430,
    successRate: "78%",
    lastActive: "12 min ago",
    category: "Analytics",
    rules: [
      { id: "r1", label: "Data sources", value: "Monitor Twitter/X, Reddit, GitHub activity, and on-chain tx volume spikes." },
      { id: "r2", label: "Trend threshold", value: "Only flag a trend when engagement growth exceeds 300% in a 6-hour window." },
      { id: "r3", label: "Exclusions", value: "Ignore projects with no GitHub repo or fewer than 50 on-chain addresses." },
      { id: "r4", label: "Alert cooldown", value: "Do not re-alert on the same trend within 48 hours." },
      { id: "r5", label: "Confidence tagging", value: "Tag each trend with a confidence score (Low/Medium/High) before emitting." },
    ],
    budget: "$200 / month (API costs)",
    riskLevel: "low",
    schedule: "Every 6 hours",
    walletAddress: "0xA9c1...d22B",
    deployedAt: "Feb 14, 2025",
    activityLog: [
      { time: "12m ago", event: "Trend detected", detail: "HIGH confidence: Base L2 TVL surged 280% — 4 sources agree", kind: "success" },
      { time: "6h ago", event: "Alert sent", detail: "MEDIUM confidence: New DEX on Arbitrum gaining traction", kind: "success" },
      { time: "12h ago", event: "Trend skipped", detail: "Growth spike isolated to single bot account — filtered out", kind: "info" },
    ],
  },
  {
    id: "taskforgepro",
    name: "TaskForge Pro",
    description: "Automates repetitive workflows across tools, APIs, and services using event-driven pipelines.",
    avatar: "/figmaAssets/avatars-6.svg",
    status: "active",
    type: "Automation",
    earnings: "+$1,800",
    trades: 922,
    successRate: "96%",
    lastActive: "4 min ago",
    category: "Productivity",
    rules: [
      { id: "r1", label: "Trigger types", value: "Only respond to: webhook events, scheduled cron jobs, and manual triggers." },
      { id: "r2", label: "Rate limit", value: "Do not execute more than 100 actions per hour across all workflows." },
      { id: "r3", label: "Error handling", value: "On failure, retry up to 3 times then send an alert and halt the workflow." },
      { id: "r4", label: "Secrets management", value: "Never log or expose API keys — use environment vault exclusively." },
      { id: "r5", label: "Audit trail", value: "Log every action with timestamp, input, output, and execution duration." },
    ],
    budget: "$100 / month",
    riskLevel: "low",
    schedule: "Event-driven",
    walletAddress: "N/A",
    deployedAt: "Mar 1, 2025",
    activityLog: [
      { time: "4m ago", event: "Workflow executed", detail: "Synced 42 records from Notion → Airtable successfully", kind: "success" },
      { time: "1h ago", event: "Workflow executed", detail: "Sent weekly digest email to 3 recipients", kind: "success" },
      { time: "3h ago", event: "Retry triggered", detail: "Webhook timeout on Zapier endpoint — retrying (2/3)", kind: "warn" },
    ],
  },
  {
    id: "opscommander",
    name: "Ops Commander",
    description: "Coordinates multi-step workflows across systems and APIs with real-time monitoring and rollback.",
    avatar: "/figmaAssets/avatars-8.svg",
    status: "active",
    type: "Operations",
    earnings: "+$3,200",
    trades: 581,
    successRate: "91%",
    lastActive: "8 min ago",
    category: "Productivity",
    rules: [
      { id: "r1", label: "Workflow scope", value: "Only orchestrate tasks within pre-approved service integrations." },
      { id: "r2", label: "Rollback policy", value: "Auto-rollback any multi-step pipeline that fails at step 3 or later." },
      { id: "r3", label: "Concurrency limit", value: "Run no more than 5 workflows in parallel at any time." },
      { id: "r4", label: "Human checkpoints", value: "Require manual approval for any workflow touching financial data." },
      { id: "r5", label: "SLA monitoring", value: "Alert if any workflow takes longer than 2× its expected duration." },
    ],
    budget: "$300 / month",
    riskLevel: "medium",
    schedule: "Continuous",
    walletAddress: "0xB82d...3fC9",
    deployedAt: "Feb 1, 2025",
    activityLog: [
      { time: "8m ago", event: "Pipeline complete", detail: "5-step data ingestion pipeline finished in 14s", kind: "success" },
      { time: "2h ago", event: "Checkpoint triggered", detail: "Financial data step — awaiting human approval", kind: "warn" },
      { time: "5h ago", event: "SLA alert", detail: "Reporting pipeline exceeded 2× expected duration — investigated", kind: "warn" },
    ],
  },
  {
    id: "invoicebot",
    name: "Invoice Bot",
    description: "Generates invoices, tracks payment status, and automates billing workflows for recurring clients.",
    avatar: "/figmaAssets/avatars-4.svg",
    status: "inactive",
    type: "Finance",
    earnings: "+$620",
    trades: 88,
    successRate: "100%",
    lastActive: "2 days ago",
    category: "Finance",
    rules: [
      { id: "r1", label: "Invoice format", value: "Always generate invoices in PDF with line items, tax, and payment terms." },
      { id: "r2", label: "Reminder schedule", value: "Send reminders at 7 days, 3 days, and 1 day before due date." },
      { id: "r3", label: "Late fees", value: "Apply a 2% monthly late fee only after 14 days overdue." },
      { id: "r4", label: "Currency", value: "Support USD and USDC invoices; convert using real-time rates." },
      { id: "r5", label: "Client whitelist", value: "Only bill from the approved client list — no unsanctioned invoices." },
    ],
    budget: "$50 / month",
    riskLevel: "low",
    schedule: "Monthly + on-demand",
    walletAddress: "0xD11f...7aB4",
    deployedAt: "Dec 15, 2024",
    activityLog: [
      { time: "2d ago", event: "Deactivated", detail: "Manual pause — end of billing cycle", kind: "warn" },
      { time: "3d ago", event: "Invoice sent", detail: "$4,500 invoice dispatched to Acme Corp — due in 30 days", kind: "success" },
      { time: "3d ago", event: "Reminder sent", detail: "7-day reminder sent to BetaTech for $1,200 outstanding", kind: "success" },
    ],
  },
  {
    id: "dealcloser",
    name: "Deal Closer",
    description: "Negotiates and executes transactions between agents using escrow and conditional smart contract payments.",
    avatar: "/figmaAssets/avatars-3.svg",
    status: "paused",
    type: "Negotiation",
    earnings: "+$9,800",
    trades: 134,
    successRate: "84%",
    lastActive: "1 day ago",
    category: "DeFi",
    rules: [
      { id: "r1", label: "Negotiation floor", value: "Never accept a deal below 80% of target price without human approval." },
      { id: "r2", label: "Escrow requirement", value: "All deals above $1,000 must use smart contract escrow." },
      { id: "r3", label: "Counterparty verification", value: "Verify counterparty identity and reputation score before proceeding." },
      { id: "r4", label: "Time limit", value: "Auto-cancel negotiations that exceed 48 hours without resolution." },
      { id: "r5", label: "Dispute handling", value: "Flag disputed deals for human arbitration immediately." },
    ],
    budget: "$5,000 / deal cap",
    riskLevel: "high",
    schedule: "On-demand",
    walletAddress: "0xE44a...8cD1",
    deployedAt: "Mar 5, 2025",
    activityLog: [
      { time: "1d ago", event: "Paused by user", detail: "Agent paused — reviewing recent high-value deal", kind: "warn" },
      { time: "2d ago", event: "Deal closed", detail: "$3,200 escrow released — both parties confirmed", kind: "success" },
      { time: "3d ago", event: "Negotiation started", detail: "Opened deal with SwarmAlpha for compute resources", kind: "info" },
    ],
  },
  {
    id: "swarmalpha",
    name: "SwarmAlpha",
    description: "Coordinates multiple sub-agents to execute complex strategies in parallel across DeFi and data pipelines.",
    avatar: "/figmaAssets/avatars-7.svg",
    status: "active",
    type: "Orchestration",
    earnings: "+$21,400",
    trades: 1203,
    successRate: "80%",
    lastActive: "1 min ago",
    category: "DeFi",
    rules: [
      { id: "r1", label: "Swarm composition", value: "Coordinate only pre-approved sub-agents: AlphaFlow, Yield Pilot, Risk Sentinel." },
      { id: "r2", label: "Consensus requirement", value: "Require agreement from at least 2 sub-agents before executing a joint action." },
      { id: "r3", label: "Budget allocation", value: "Never allocate more than 40% of total budget to a single sub-agent." },
      { id: "r4", label: "Kill switch", value: "Halt all sub-agents immediately if portfolio drops 20% in any 4-hour window." },
      { id: "r5", label: "Reporting", value: "Emit a consolidated summary of all sub-agent actions every 12 hours." },
    ],
    budget: "$50,000",
    riskLevel: "high",
    schedule: "Continuous (24/7)",
    walletAddress: "0xF77b...2eA3",
    deployedAt: "Mar 18, 2025",
    activityLog: [
      { time: "1m ago", event: "Swarm action", detail: "Coordinated BUY across AlphaFlow + YieldPilot — $12k deployed", kind: "success" },
      { time: "30m ago", event: "Consensus reached", detail: "3/3 sub-agents agreed on ETH accumulation signal", kind: "success" },
      { time: "2h ago", event: "Sub-agent halted", detail: "Risk Sentinel flagged anomaly — DealCloser paused temporarily", kind: "warn" },
    ],
  },
  {
    id: "paystream",
    name: "Pay Stream",
    description: "Executes real-time payments for APIs and services using x402 protocols and smart contracts.",
    avatar: "/figmaAssets/avatars-1.svg",
    status: "inactive",
    type: "Payments",
    earnings: "+$950",
    trades: 67,
    successRate: "94%",
    lastActive: "5 days ago",
    category: "Finance",
    rules: [
      { id: "r1", label: "Payment whitelist", value: "Only pay to pre-approved API providers: OpenAI, Anthropic, Pinecone, Infura." },
      { id: "r2", label: "Max single payment", value: "Never authorize a single payment exceeding $500 without human confirmation." },
      { id: "r3", label: "Budget cap", value: "Do not exceed monthly spend budget of $2,000 across all services." },
      { id: "r4", label: "Retry logic", value: "Retry failed payments up to 3 times with 60-second intervals." },
      { id: "r5", label: "Receipt logging", value: "Store cryptographic proof of every payment on-chain via x402 receipt." },
    ],
    budget: "$2,000 / month",
    riskLevel: "medium",
    schedule: "On-demand (event-driven)",
    walletAddress: "0x3A1b...9eC7",
    deployedAt: "Jan 28, 2025",
    activityLog: [
      { time: "5d ago", event: "Deactivated", detail: "Agent stopped — budget cycle reset pending", kind: "warn" },
      { time: "6d ago", event: "Payment sent", detail: "$149.00 to Anthropic API — monthly invoice settled", kind: "success" },
      { time: "6d ago", event: "Payment failed", detail: "Infura endpoint timeout — retrying (1/3)", kind: "warn" },
      { time: "6d ago", event: "Payment sent", detail: "$12.50 to Infura — retry successful", kind: "success" },
    ],
  },
];
