module.exports = {
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "brain-v1baby-blue-100": "var(--brain-v1baby-blue-100)",
        "brain-v1baby-blue-15": "var(--brain-v1baby-blue-15)",
        "brain-v1baby-blue-30": "var(--brain-v1baby-blue-30)",
        "brain-v1baby-blue-5": "var(--brain-v1baby-blue-5)",
        "brain-v1baby-blue-60": "var(--brain-v1baby-blue-60)",
        "brain-v1dark-dark-purple": "var(--brain-v1dark-dark-purple)",
        "brain-v1dark-green": "var(--brain-v1dark-green)",
        "brain-v1dark-orange": "var(--brain-v1dark-orange)",
        "brain-v1dark-pink-red": "var(--brain-v1dark-pink-red)",
        "brain-v1dark-purple": "var(--brain-v1dark-purple)",
        "brain-v1green": "var(--brain-v1green)",
        "brain-v1headerfooterbg": "var(--brain-v1headerfooterbg)",
        "brain-v1highlight-dropdown-bg": "var(--brain-v1highlight-dropdown-bg)",
        "brain-v1light-orange": "var(--brain-v1light-orange)",
        "brain-v1pink-red": "var(--brain-v1pink-red)",
        "brain-v1purple": "var(--brain-v1purple)",
        "brain-v1stroke-2": "var(--brain-v1stroke-2)",
        "brain-v1white": "var(--brain-v1white)",
        "brain-v1white-30": "var(--brain-v1white-30)",
        "braindark-purple": "var(--braindark-purple)",
        brainpurple: "var(--brainpurple)",
        "shared-colorsbaby-blue-5": "var(--shared-colorsbaby-blue-5)",
        "shared-colorsbaby-blue-60": "var(--shared-colorsbaby-blue-60)",
        "shared-colorsheaderfooterbg": "var(--shared-colorsheaderfooterbg)",
        "shared-colorsstroke-2": "var(--shared-colorsstroke-2)",
        white: "var(--white)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "subheading-2x-small": "var(--subheading-2x-small-font-family)",
        "plus-jakarta": ['"Plus Jakarta Sans"', "sans-serif"],
        outfit: ['"Outfit"', "sans-serif"],
        "space-grotesk": ['"Space Grotesk"', "sans-serif"],
        mono: ['"JetBrains Mono"', "ui-monospace", "monospace"],
        sans: [
          '"Plus Jakarta Sans"',
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
  darkMode: ["class"],
};
