module.exports = {
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "brain-v1baby-blue-100": "var(--brain-v1baby-blue-100)",
        "brain-v1baby-blue-15": "var(--brain-v1baby-blue-15)",
        "brain-v1baby-blue-15-hover": "var(--brain-v1baby-blue-15-hover)",
        "brain-v1baby-blue-30": "var(--brain-v1baby-blue-30)",
        "brain-v1baby-blue-5": "var(--brain-v1baby-blue-5)",
        "brain-v1baby-blue-60": "var(--brain-v1baby-blue-60)",
        "brain-v1dark-dark-purple": "var(--brain-v1dark-dark-purple)",
        "brain-v1dark-green": "var(--brain-v1dark-green)",
        "brain-v1dark-orange": "var(--brain-v1dark-orange)",
        "brain-v1dark-orange-hover": "var(--brain-v1dark-orange-hover)",
        "brain-v1dark-pink-red": "var(--brain-v1dark-pink-red)",
        "brain-v1dark-purple": "var(--brain-v1dark-purple)",
        "brain-v1dark-purple-hover": "var(--brain-v1dark-purple-hover)",
        "brain-v1green": "var(--brain-v1green)",
        "brain-v1headerfooterbg": "var(--brain-v1headerfooterbg)",
        "brain-v1highlight-dropdown-bg": "var(--brain-v1highlight-dropdown-bg)",
        "brain-v1light-orange": "var(--brain-v1light-orange)",
        "brain-v1pink-red": "var(--brain-v1pink-red)",
        "brain-v1purple": "var(--brain-v1purple)",
        "brain-v1purple-hover": "var(--brain-v1purple-hover)",
        "brain-v1stroke-2": "var(--brain-v1stroke-2)",
        "brain-v1white": "var(--brain-v1white)",
        "brain-v1white-30": "var(--brain-v1white-30)",
        "brain-v1baby-blue-80": "var(--brain-v1baby-blue-80)",
        "brain-v1dark-green-hover": "var(--brain-v1dark-green-hover)",
        "brain-v1dark-pink-red-hover": "var(--brain-v1dark-pink-red-hover)",
        "brain-v1error-text": "var(--brain-v1error-text)",
        "brain-v1headerfooterbg-hover": "var(--brain-v1headerfooterbg-hover)",
        "brain-v1item-hover": "var(--brain-v1item-hover)",
        "brain-v1row-hover": "var(--brain-v1row-hover)",
        "brain-v1stroke-2-hover": "var(--brain-v1stroke-2-hover)",
        "braindark-purple": "var(--braindark-purple)",
        brainpurple: "var(--brainpurple)",
        "shared-colorsbaby-blue-5": "var(--shared-colorsbaby-blue-5)",
        "shared-colorsbaby-blue-60": "var(--shared-colorsbaby-blue-60)",
        "shared-colorsheaderfooterbg": "var(--shared-colorsheaderfooterbg)",
        "shared-colorsstroke-2": "var(--shared-colorsstroke-2)",
        "brand-telegram": "var(--brand-telegram)",
        "brand-whatsapp": "var(--brand-whatsapp)",
        "doc-paper-100": "var(--doc-paper-100)",
        "doc-paper-200": "var(--doc-paper-200)",
        "doc-paper-300": "var(--doc-paper-300)",
        "doc-paper-rule-light": "var(--doc-paper-rule-light)",
        "doc-paper-rule": "var(--doc-paper-rule)",
        "doc-paper-rule-strong": "var(--doc-paper-rule-strong)",
        "doc-paper-ink-300": "var(--doc-paper-ink-300)",
        "doc-paper-ink-400": "var(--doc-paper-ink-400)",
        "doc-paper-ink-500": "var(--doc-paper-ink-500)",
        "doc-paper-ink-700": "var(--doc-paper-ink-700)",
        "doc-paper-ink-800": "var(--doc-paper-ink-800)",
        "doc-paper-ink-900": "var(--doc-paper-ink-900)",
        white: "var(--white)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "subheading-2x-small": "var(--subheading-2x-small-font-family)",
        "plus-jakarta": ['"Plus Jakarta Sans"', "sans-serif"],
        outfit: ['"Outfit"', "sans-serif"],
        "space-grotesk": ['"Space Grotesk"', "sans-serif"],
        mono: ['"JetBrains Mono"', "ui-monospace", "monospace"],
        sans: [
          '"Plus Jakarta Sans"',
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        // Named radii for the de-facto scale (docs/design-audit.md §3).
        // Values are the existing measured ones, so adoption is visually neutral.
        row: "var(--radius-row)", // 12px — list/table rows
        panel: "var(--radius-panel)", // 16px — cards and panels
        modal: "var(--radius-modal)", // 24px — dialogs and modals
        pill: "var(--radius-pill)", // 100px — pills and chip tracks
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
  darkMode: ["class"],
};
