/**
 * One-time starter seed for a freshly created DURABLE tenant (config.brainDurableTenancy).
 *
 * Runs the three bundled demo documents (server/assets/demo-seed/, generated by
 * scripts/generate-demo-seed.ts) through the SAME pipeline the Add Source modal uses:
 *   local sourceDocuments metadata record → brain-core /raw/ingest → /raw/{id}/extract.
 * That fires brain-core's full interpretation/projection/wiki path, so the Home and
 * Finances numbers come from whatever the tenant's ledger actually derives — nothing
 * is hardcoded client-side.
 *
 * Invoked exactly once, fire-and-forget, right after tenant creation in auth.ts.
 * Failures are LOUD (console.error + "failed"/"unavailable" document statuses the UI
 * shows honestly) but never block the login/session path. It is never re-run for an
 * existing tenant: the caller only invokes it in the create-tenant branch.
 */

import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { existsSync } from "node:fs";
import { storage } from "../storage";
import { ingestRawDocument, pollRawExtraction, BrainApiError, type RawSourceType } from "./client";
import { extractStatusForJob } from "./extractStatus";
import type { ExtractStatus } from "../storage";

const SEED_DIR = join(process.cwd(), "server", "assets", "demo-seed");

interface SeedFile {
  filename: string;
  mimeType: string;
  sourceType: RawSourceType;
  category: string;
}

/** The bundled June-2026 starter scenario (internally consistent figures). */
const SEED_FILES: SeedFile[] = [
  {
    filename: "bank_statement_2026-06.pdf",
    mimeType: "application/pdf",
    sourceType: "pdf_upload",
    category: "bank_statement",
  },
  {
    filename: "ar_aging_2026-06-30.xlsx",
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    sourceType: "csv_upload",
    category: "ar_aging",
  },
  {
    filename: "payroll_register_2026-06.xlsx",
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    sourceType: "csv_upload",
    category: "payroll",
  },
];

/**
 * Ingest the bundled seed documents into the user's (just-created) tenant using the
 * provided ingest-capable token (the AGENT token in durable mode - the durable member
 * token lacks the raw:write scope; verified live 2026-07-24). Sequential on purpose:
 * predictable ordering in the documents list and no burst against /raw/ingest. Each
 * file is independent — one failure does not stop the others.
 */
export async function seedTenantDocuments(appUserId: string, ingestToken: string): Promise<void> {
  for (const file of SEED_FILES) {
    const path = join(SEED_DIR, file.filename);
    if (!existsSync(path)) {
      console.error(`[brain-seed] missing bundled seed asset ${path} - skipping (run scripts/generate-demo-seed.ts)`);
      continue;
    }
    let doc;
    try {
      const bytes = await readFile(path);
      // 1. Local metadata record (bytes are NOT persisted here - they live in Brain).
      doc = await storage.createSourceDocument({
        userId: appUserId,
        name: file.filename,
        size: bytes.length,
        mimeType: file.mimeType,
        category: file.category,
        sourceType: file.sourceType,
        extractStatus: "pending",
      });

      // 2. Ingest bytes to brain-core.
      const ingest = await ingestRawDocument(ingestToken, {
        sourceType: file.sourceType,
        bytes: new Uint8Array(bytes),
        filename: file.filename,
        mimeType: file.mimeType,
      });
      await storage.updateSourceDocumentExtraction(appUserId, doc.id, {
        rawId: ingest.raw_id,
        sha256: ingest.sha256,
        extractStatus: "ingested",
      });

      // 3. Trigger extraction and WAIT for brain-core's job to settle. The extract call is
      // async (first response is 202/"queued" with parsed_id: null), so returning on the
      // first response recorded "extracted" with a null parsed_id forever. Nobody is waiting
      // on this seed (fire-and-forget after tenant create), so polling here is free.
      // Status mapping mirrors the /api/integrations/documents/ingest route
      // (422 → unsupported; 404/other → unavailable).
      let extractStatus: ExtractStatus = "extracting";
      let parsedId: string | null = null;
      let confidence: string | null = null;
      try {
        const extract = await pollRawExtraction(ingestToken, ingest.raw_id);
        extractStatus = extractStatusForJob(extract);
        if (extractStatus === "failed") {
          console.warn(`[brain-seed] extraction ${extract.status} for ${file.filename}: ${extract.error ?? "no detail"}`);
        } else if (extractStatus === "extracting") {
          // Budget exhausted while still queued/running - say so instead of claiming success.
          console.warn(`[brain-seed] extraction still ${extract.status ?? "pending"} for ${file.filename} after poll budget`);
        }
        parsedId = extract.parsed_id;
        confidence = extract.confidence !== null ? String(extract.confidence) : null;
      } catch (err) {
        if (err instanceof BrainApiError && err.status === 422) {
          extractStatus = "unsupported";
        } else {
          const detail = err instanceof BrainApiError ? `status=${err.status}` : (err as Error).message;
          console.warn(`[brain-seed] extract failed for ${file.filename} (${detail})`);
          extractStatus = "unavailable";
        }
      }
      await storage.updateSourceDocumentExtraction(appUserId, doc.id, { extractStatus, parsedId, confidence });
      console.log(`[brain-seed] ${file.filename} → ${extractStatus}`);
    } catch (err) {
      console.error(`[brain-seed] ingest failed for ${file.filename}:`, (err as Error).message);
      if (doc) {
        await storage
          .updateSourceDocumentExtraction(appUserId, doc.id, { extractStatus: "failed" })
          .catch(() => undefined);
      }
    }
  }
}
