/**
 * One-time starter seed for a freshly created DURABLE tenant (config.brainDurableTenancy).
 *
 * Runs the three bundled demo documents (server/assets/demo-seed/, generated by
 * scripts/generate-demo-seed.ts) through the SAME pipeline the Add Source modal uses:
 *   local sourceDocuments metadata record → brain-core /raw/ingest → /raw/{id}/extract.
 * That fires brain-core's full interpretation/projection/wiki path, so the Home and
 * Finances numbers come from whatever the tenant's ledger actually derives — nothing
 * is hardcoded client-side.
 *
 * Invoked exactly once, fire-and-forget, right after tenant creation in auth.ts.
 * Failures are LOUD (console.error + "failed"/"unavailable" document statuses the UI
 * shows honestly) but never block the login/session path. It is never re-run for an
 * existing tenant: the caller only invokes it in the create-tenant branch.
 */

import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { existsSync } from "node:fs";
import { storage } from "../storage";
import { ingestRawDocument, pollRawExtraction, BrainApiError, type RawSourceType } from "./client";
import { extractStatusForJob } from "./extractStatus";
import type { ExtractStatus } from "../storage";

const SEED_DIR = join(process.cwd(), "server", "assets", "demo-seed");

interface SeedFile {
  filename: string;
  mimeType: string;
  sourceType: RawSourceType;
  category: string;
}

const XLSX_MIME = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

/**
 * The bundled June-2026 starter scenario (internally consistent figures - see the
 * reconciliation rules at the top of scripts/generate-demo-seed.ts).
 *
 * `category` MUST be one of the CategoryId values the Add Source modal knows
 * ("bank" | "crypto" | "accounting" | "payroll" | "tax" | "payments" | "documents"),
 * because the category badges group real documents by exactly that field. It is a
 * BFF-local label: brain-core is only ever sent sourceType + mimeType + source_schema,
 * so there is no upstream category vocabulary to match.
 *
 * `sourceType` is brain-core's own: only "pdf_upload" and "csv_upload" exist, and
 * "csv_upload" is the correct value for XLSX too.
 */
export const SEED_FILES: SeedFile[] = [
  {
    filename: "bank_statement_2026-06.pdf",
    mimeType: "application/pdf",
    sourceType: "pdf_upload",
    category: "bank",
  },
  {
    filename: "ar_aging_2026-06-30.xlsx",
    mimeType: XLSX_MIME,
    sourceType: "csv_upload",
    category: "accounting",
  },
  {
    filename: "payroll_register_2026-06.xlsx",
    mimeType: XLSX_MIME,
    sourceType: "csv_upload",
    category: "payroll",
  },
  {
    filename: "crypto_wallet_2026-06.csv",
    mimeType: "text/csv",
    sourceType: "csv_upload",
    category: "crypto",
  },
  {
    filename: "form_1120_2025.pdf",
    mimeType: "application/pdf",
    sourceType: "pdf_upload",
    category: "tax",
  },
];

/**
 * Ingest the bundled seed documents into the user's (just-created) tenant using the
 * provided ingest-capable token (the AGENT token in durable mode - the durable member
 * token lacks the raw:write scope; verified live 2026-07-24). Sequential on purpose:
 * predictable ordering in the documents list and no burst against /raw/ingest. Each
 * file is independent — one failure does not stop the others.
 */
export async function seedTenantDocuments(appUserId: string, ingestToken: string): Promise<void> {
  const run = runSeed(appUserId, ingestToken);
  inFlightSeeds.add(run);
  try {
    await run;
  } finally {
    inFlightSeeds.delete(run);
  }
}

/**
 * Seeding is fire-and-forget off the login path, so nothing normally awaits it. This
 * handle lets a caller that DOES need it to be finished - a test asserting on the
 * resulting documents, or a graceful-shutdown path - wait for every in-flight run to
 * settle instead of racing it with a sleep.
 */
const inFlightSeeds = new Set<Promise<unknown>>();

/** Wall-clock budget for whenSeedsSettle(). Comfortably longer than a real seed run
 *  (5 files x brain-core's async extract poll) so only a genuinely stuck run trips it. */
const SETTLE_TIMEOUT_MS = 5 * 60_000;

export async function whenSeedsSettle(timeoutMs = SETTLE_TIMEOUT_MS): Promise<boolean> {
  const deadline = Date.now() + timeoutMs;
  // Each pass drains the current set, then yields so the `finally` blocks above can
  // remove the settled entries before we look for runs that started in the meantime.
  // Bounded by wall clock, not by pass count: a seed whose fetch stalls would otherwise
  // park the caller (a test barrier, a shutdown hook) forever.
  while (inFlightSeeds.size > 0) {
    const remaining = deadline - Date.now();
    if (remaining <= 0) break;
    let timer: NodeJS.Timeout | undefined;
    await Promise.race([
      Promise.allSettled([...inFlightSeeds]),
      new Promise((r) => {
        timer = setTimeout(r, remaining);
      }),
    ]);
    if (timer) clearTimeout(timer);
    await new Promise((r) => setTimeout(r, 0));
  }
  if (inFlightSeeds.size > 0) {
    // Never return silently as if the work were done - a caller that assumes a clean
    // slate would otherwise attribute the stalled run's side effects to whatever runs next.
    console.warn(`[brain-seed] ${inFlightSeeds.size} seed run(s) still in flight after ${timeoutMs}ms`);
    return false;
  }
  return true;
}

async function runSeed(appUserId: string, ingestToken: string): Promise<void> {
  for (const file of SEED_FILES) {
    const path = join(SEED_DIR, file.filename);
    if (!existsSync(path)) {
      console.error(`[brain-seed] missing bundled seed asset ${path} - skipping (run scripts/generate-demo-seed.ts)`);
      continue;
    }
    let doc;
    try {
      const bytes = await readFile(path);
      // 1. Local metadata record (bytes are NOT persisted here - they live in Brain).
      doc = await storage.createSourceDocument({
        userId: appUserId,
        name: file.filename,
        size: bytes.length,
        mimeType: file.mimeType,
        category: file.category,
        sourceType: file.sourceType,
        extractStatus: "pending",
      });

      // 2. Ingest bytes to brain-core.
      const ingest = await ingestRawDocument(ingestToken, {
        sourceType: file.sourceType,
        bytes: new Uint8Array(bytes),
        filename: file.filename,
        mimeType: file.mimeType,
      });
      await storage.updateSourceDocumentExtraction(appUserId, doc.id, {
        rawId: ingest.raw_id,
        sha256: ingest.sha256,
        extractStatus: "ingested",
      });

      // 3. Trigger extraction and WAIT for brain-core's job to settle. The extract call is
      // async (first response is 202/"queued" with parsed_id: null), so returning on the
      // first response recorded "extracted" with a null parsed_id forever. Nobody is waiting
      // on this seed (fire-and-forget after tenant create), so polling here is free.
      // Status mapping mirrors the /api/integrations/documents/ingest route
      // (422 → unsupported; 404/other → unavailable).
      let extractStatus: ExtractStatus = "extracting";
      let parsedId: string | null = null;
      let confidence: string | null = null;
      try {
        const extract = await pollRawExtraction(ingestToken, ingest.raw_id);
        extractStatus = extractStatusForJob(extract);
        if (extractStatus === "failed") {
          console.warn(`[brain-seed] extraction ${extract.status} for ${file.filename}: ${extract.error ?? "no detail"}`);
        } else if (extractStatus === "extracting") {
          // Budget exhausted while still queued/running - say so instead of claiming success.
          console.warn(`[brain-seed] extraction still ${extract.status ?? "pending"} for ${file.filename} after poll budget`);
        }
        parsedId = extract.parsed_id;
        confidence = extract.confidence !== null ? String(extract.confidence) : null;
      } catch (err) {
        if (err instanceof BrainApiError && err.status === 422) {
          extractStatus = "unsupported";
        } else {
          const detail = err instanceof BrainApiError ? `status=${err.status}` : (err as Error).message;
          console.warn(`[brain-seed] extract failed for ${file.filename} (${detail})`);
          extractStatus = "unavailable";
        }
      }
      await storage.updateSourceDocumentExtraction(appUserId, doc.id, { extractStatus, parsedId, confidence });
      console.log(`[brain-seed] ${file.filename} → ${extractStatus}`);
    } catch (err) {
      console.error(`[brain-seed] ingest failed for ${file.filename}:`, (err as Error).message);
      if (doc) {
        await storage
          .updateSourceDocumentExtraction(appUserId, doc.id, { extractStatus: "failed" })
          .catch(() => undefined);
      }
    }
  }
}
