/**
 * Source-scan guards for settings navigation, audit-log redirect, and
 * developer endpoint scope consistency.
 *
 * #66 — Catch a broken old audit-log bookmark before it ships
 *   Old bookmarks and assistant citations still point to /audit-log. App.tsx
 *   registers an AuditLogRedirect that forwards them to /inbox with the search
 *   string intact and replace:true so the stale URL never stays in history.
 *   This test pins that contract so a future cleanup of App.tsx cannot silently
 *   turn old deep-links into a NotFound page.
 *
 * #76 — Catch Settings QA checks that quietly stop running after a control is
 *   restyled. Every NAV_ITEMS entry generates a `settings-nav-${id}` testid;
 *   every id must remain in VALID_SECTIONS so direct URL access still works.
 *   This pins the nav registry so a restyle that renames a testid or removes an
 *   item from VALID_SECTIONS fails before it ships.
 *
 * #29 — Catch drift between the docs and the real endpoint scopes before it ships.
 *   SCOPE_OPTIONS in DevelopersSection must be a perfect subset of API_KEY_SCOPES
 *   in server/developers.ts (no invented scopes in the UI). API_ENDPOINTS scopes
 *   must be null (no scope required) or a known scope from API_KEY_SCOPES (no
 *   phantom scopes shown to developers).
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";

const APP = "client/src/App.tsx";
const SETTINGS = "client/src/pages/SettingsPage.tsx";
const DEVELOPERS_TSX = "client/src/components/settings/DevelopersSection.tsx";
const DEVELOPERS_SERVER = "server/developers.ts";

// ─── #66: Audit-log redirect ──────────────────────────────────────────────────

describe("AuditLogRedirect contract (#66)", () => {
  it("App.tsx registers a route at /audit-log", () => {
    const src = readFileSync(APP, "utf8");
    expect(src, 'App.tsx must have path="/audit-log"').toMatch(/path="\/audit-log"/);
  });

  it("AuditLogRedirect navigates to /inbox, not a stale or removed path", () => {
    const src = readFileSync(APP, "utf8");
    const redirectStart = src.indexOf("AuditLogRedirect");
    expect(redirectStart, "AuditLogRedirect component not found in App.tsx").toBeGreaterThan(-1);
    // Capture text from the component declaration through its closing brace.
    const snippet = src.slice(redirectStart, redirectStart + 600);
    expect(snippet, "AuditLogRedirect must navigate to /inbox").toMatch(/navigate.*\/inbox/);
  });

  it("AuditLogRedirect uses replace:true so /audit-log never stays in browser history", () => {
    const src = readFileSync(APP, "utf8");
    const redirectStart = src.indexOf("AuditLogRedirect");
    const snippet = src.slice(redirectStart, redirectStart + 600);
    expect(snippet, 'AuditLogRedirect must pass { replace: true }').toMatch(/replace.*true|replace:\s*true/);
  });

  it("AuditLogRedirect forwards the search string so ?record= deep-links land on the right row", () => {
    const src = readFileSync(APP, "utf8");
    const redirectStart = src.indexOf("AuditLogRedirect");
    const snippet = src.slice(redirectStart, redirectStart + 600);
    // The component must read search (useSearch) and embed it in the navigate target.
    expect(snippet, "AuditLogRedirect must read useSearch() and embed it in navigate").toMatch(/search/);
    // Navigate call must reference the search variable inside the /inbox path.
    expect(snippet, "Navigate target must include search param").toMatch(/\/inbox.*\$\{search\}|\$\{search\}.*\/inbox/);
  });

  it("/audit-log route component is AuditLogRedirect (not an inline component or dead import)", () => {
    const src = readFileSync(APP, "utf8");
    expect(src).toMatch(/path="\/audit-log"\s+component=\{AuditLogRedirect\}/);
  });
});

// ─── #76: Settings nav testids ───────────────────────────────────────────────

describe("Settings nav testids contract (#76)", () => {
  it("NAV_ITEMS entries all generate settings-nav-${id} testids via the template", () => {
    const src = readFileSync(SETTINGS, "utf8");
    // The testid is generated by template literal in the map — not hardcoded per item.
    expect(src, 'Settings nav testids must use `settings-nav-${id}` template').toMatch(
      /data-testid=\{`settings-nav-\$\{id\}`\}/,
    );
  });

  it("every NAV_ITEMS id appears in VALID_SECTIONS so it is reachable by URL", () => {
    const src = readFileSync(SETTINGS, "utf8");

    // Parse the NAV_ITEMS block: extract id: "..." entries.
    const navMatch = src.match(/const NAV_ITEMS[^=]*=\s*\[([\s\S]*?)\];/);
    expect(navMatch, "NAV_ITEMS constant not found in SettingsPage.tsx").not.toBeNull();
    const navBlock = navMatch![1];
    const navIds = [...navBlock.matchAll(/id:\s*"([^"]+)"/g)].map((m) => m[1]);
    expect(navIds.length, "NAV_ITEMS must have at least one entry").toBeGreaterThan(0);

    // Parse VALID_SECTIONS.
    const vsMatch = src.match(/VALID_SECTIONS[^=]*=\s*\[([^\]]+)\]/);
    expect(vsMatch, "VALID_SECTIONS constant not found in SettingsPage.tsx").not.toBeNull();
    const validSections = [...vsMatch![1].matchAll(/"([^"]+)"/g)].map((m) => m[1]);

    for (const id of navIds) {
      expect(
        validSections,
        `NAV_ITEMS id "${id}" is not in VALID_SECTIONS — URL-based navigation to /settings?section=${id} will silently fall back to the default section`,
      ).toContain(id);
    }
  });

  it("VALID_SECTIONS drives both URL parsing and the SectionContent map", () => {
    const src = readFileSync(SETTINGS, "utf8");
    // VALID_SECTIONS must be used in the section-resolution logic.
    expect(src, "VALID_SECTIONS must gate URL-param validation").toMatch(
      /VALID_SECTIONS\.includes.*as Section/,
    );
    // SectionContent must be an object literal keyed by section.
    expect(src, "SectionContent map must exist").toMatch(/const SectionContent\s*=/);
  });
});

// ─── #29: Endpoint scope drift ───────────────────────────────────────────────

describe("Developer endpoint scope consistency (#29)", () => {
  it("SCOPE_OPTIONS in the UI only lists scopes that are in the server's API_KEY_SCOPES", () => {
    const serverSrc = readFileSync(DEVELOPERS_SERVER, "utf8");
    const clientSrc = readFileSync(DEVELOPERS_TSX, "utf8");

    // Parse API_KEY_SCOPES from server/developers.ts.
    const serverMatch = serverSrc.match(/API_KEY_SCOPES\s*=\s*\[([^\]]+)\]/);
    expect(serverMatch, "API_KEY_SCOPES not found in server/developers.ts").not.toBeNull();
    const serverScopes = [...serverMatch![1].matchAll(/"([^"]+)"/g)].map((m) => m[1]);
    expect(serverScopes.length, "API_KEY_SCOPES must be non-empty").toBeGreaterThan(0);

    // Parse SCOPE_OPTIONS from DevelopersSection.tsx.
    const clientMatch = clientSrc.match(/const SCOPE_OPTIONS\s*=\s*\[([\s\S]*?)\]\s*as const/);
    expect(clientMatch, "SCOPE_OPTIONS not found in DevelopersSection.tsx").not.toBeNull();
    const clientScopes = [...clientMatch![1].matchAll(/id:\s*"([^"]+)"/g)].map((m) => m[1]);
    expect(clientScopes.length, "SCOPE_OPTIONS must be non-empty").toBeGreaterThan(0);

    for (const scope of clientScopes) {
      expect(
        serverScopes,
        `SCOPE_OPTIONS lists "${scope}" but it is not in API_KEY_SCOPES — the UI would offer a scope brain-core does not accept`,
      ).toContain(scope);
    }
  });

  it("API_ENDPOINTS in the UI only references null or known scopes", () => {
    const serverSrc = readFileSync(DEVELOPERS_SERVER, "utf8");
    const clientSrc = readFileSync(DEVELOPERS_TSX, "utf8");

    const serverMatch = serverSrc.match(/API_KEY_SCOPES\s*=\s*\[([^\]]+)\]/);
    const serverScopes = [...serverMatch![1].matchAll(/"([^"]+)"/g)].map((m) => m[1]);

    // Parse API_ENDPOINTS: extract scope: "..." or scope: null entries.
    const endpointsMatch = clientSrc.match(/const API_ENDPOINTS[^=]*=\s*\[([\s\S]*?)\];/);
    expect(endpointsMatch, "API_ENDPOINTS not found in DevelopersSection.tsx").not.toBeNull();
    const endpointsBlock = endpointsMatch![1];
    const endpointScopes = [...endpointsBlock.matchAll(/scope:\s*"([^"]+)"/g)].map((m) => m[1]);

    for (const scope of endpointScopes) {
      expect(
        serverScopes,
        `API_ENDPOINTS lists scope "${scope}" but it is not in API_KEY_SCOPES — the docs would describe a scope that does not exist`,
      ).toContain(scope);
    }
  });

  it("API_ENDPOINTS covers at least one endpoint for each server-registered scope", () => {
    const serverSrc = readFileSync(DEVELOPERS_SERVER, "utf8");
    const clientSrc = readFileSync(DEVELOPERS_TSX, "utf8");

    const serverMatch = serverSrc.match(/API_KEY_SCOPES\s*=\s*\[([^\]]+)\]/);
    const serverScopes = [...serverMatch![1].matchAll(/"([^"]+)"/g)].map((m) => m[1]);

    const endpointsMatch = clientSrc.match(/const API_ENDPOINTS[^=]*=\s*\[([\s\S]*?)\];/);
    const endpointsBlock = endpointsMatch![1];
    const documentedScopes = new Set(
      [...endpointsBlock.matchAll(/scope:\s*"([^"]+)"/g)].map((m) => m[1]),
    );

    for (const scope of serverScopes) {
      expect(
        documentedScopes,
        `Server scope "${scope}" has no matching endpoint in API_ENDPOINTS — developers cannot discover how to use this scope`,
      ).toContain(scope);
    }
  });
});
